// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cajirjydfmckjnqfbsxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhamlyanlkZm1ja2pucWZic3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjM0MzQsImV4cCI6MjA2MTIzOTQzNH0.PsUIi2_zqdf683MJ_6yXQPKv0-FKPhHsrX6BsxQnpTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);